### ISSUE TITLE
Schema example does not work

### ISSUE THREAD

**Issue by tzach** [hubt/spark-cass#1]
First I added 

```
import org.apache.spark.sql.SchemaRDD;
```

Otherwise the SchemaRDD type was missing

```
val rdd: SchemaRDD = cc.sql("SELECT * from testkeyspace.trigram limit 10")
```

Then I used 

```
rdd.foreach(println)
```

(not a.foeach)

But hit the following:

```
15/03/26 13:38:46 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 2)
com.esotericsoftware.kryo.KryoException: Unable to find class: com.datastax.spark.connector.CassandraRow
Serialization trace:
Serialization trace:
_2 (org.apache.spark.util.MutablePair)
    at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:138)
    at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:115)
    at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:610)
    at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:599)
    at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221)
    at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:732)
    at org.apache.spark.serializer.KryoDeserializationStream.readObject(KryoSerializer.scala:133)
    at org.apache.spark.serializer.DeserializationStream$$anon$1.getNext(Serializer.scala:133)
    at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:71)
    at org.apache.spark.storage.BlockManager$LazyProxyIterator$1.hasNext(BlockManager.scala:1082)
```

Thanks for the project!

**Comment by hubt** [comment]
Thanks for the report. I've fixed the two documentation issues you mentioned.

I'm still investigating the serialization error, which I am able to reproduce, I'm not sure why I didn't see it before. It appears that the classpath is not picking up /usr/local/spark-cassandra-connector/spark-cassandra-connector/target/scala-2.10/spark-cassandra-connector_2.10-1.1.0-alpha2.jar. I tried adding it to my spark-cass script and into /usr/local/spark/conf/spark-defaults.conf and it doesn't appear to fix it.

I'll look some more when I get a chance, but if you try playing around with ways of adding that jar to the classpath it might work.

**Comment by tzach** [comment]
Thanks for the prompt response and fix!
On a similar setup I have I'm using

```
../spark-cassandra-connector/spark-cassandra-connector-java/target/scala-2.10/spark-cassandra-connector-java-assembly-1.1.2-SNAPSHOT.jar 
```

note the java suffix in spark-cassandra-connector**-java** it was not always there

**Comment by hubt** [comment]
Ah that's it. I've fixed it by building the spark-cassandra-connector as an
assembly jar then including that in the
/usr/local/spark/conf/spark-defaults.conf.

I updated the Dockerfile with this patch:
https://github.com/hubt/spark-cass/commit/71f385d538e7cbf42fe5e7f86d45494cba32de46

And I've also pushed a new version of the image.

For you, you can just
cd /usr/local/spark-cassandra-connector; sbt/sbt assembly
(this produces an error about deduping, but that didn't seem to be a real
problem, so I ignored it).
Then
echo spark.executor.extraClassPath
/usr/local/spark-cassandra-connector-1.1.0-alpha2/spark-cassandra-connector-java/target/scala-2.10/spark-cassandra-connector-java-assembly-1.1.0-alpha2.jar

> > /usr/local/spark/conf/spark-defaults.conf
> > echo spark.driver.extraClassPath
> > /usr/local/spark-cassandra-connector-1.1.0-alpha2/spark-cassandra-connector-java/target/scala-2.10/spark-cassandra-connector-java-assembly-1.1.0-alpha2.jar
> > /usr/local/spark/conf/spark-defaults.conf

And then that should fix your problem I think.

I've been meaning to update to spark 1.2, but I haven't had time.

hubert

**Comment by tzach** [comment]
work like a charm :)
